waypoints:
    - point:
        x: 1.15532
        y: -42.5926
        z: 0.00393602
        function: run
    - point:
        x: -25.6319
        y: -89.4849
        z: 0.00278136
        function: run
    - point:
        x: -38.9879
        y: -108.6
        z: 0.00278518
        function: start_learning_mode
    - point:
        x: -98.6964
        y: -80.3209
        z: 0.00319454
        function: run
    - point:
        x: -137.502
        y: -53.1429
        z: -0.109764
        function: run
    - point:
        x: -143.02
        y: -41.4168
        z: 0.146939
        function: run
    - point:
        x: -114.422
        y: -2.27734
        z: 0.146962
        function: run
    - point:
        x: -85.0372
        y: 38.7167
        z: 0.146962
        function: run
    - point:
        x: -72.5491
        y: 50.1224
        z: 0.146932
        function: run
    - point:
        x: -39.1393
        y: 27.872
        z: 0.146931
        function: run
    - point:
        x: -9.1179
        y: 4.99663
        z: 0.146931
        function: run
    - point:
        x: 17.406
        y: -13.9913
        z: 0.146939
        function: suspend
