waypoints:
    - point:
        x: -25.6319
        y: -89.4849
        z: 0.00278136
        function: start_learning_mode
    - point:
        x: -38.9879
        y: -108.6
        z: 0.00278518
        function: suspend
